#!/bin/sh

LIST="á\|â\|à\|é\|è\|ê\|í\|ì\|î\|ó\|ò\|ô\|ú\|ù\|û"

if git rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

for FILE in `git diff-index --name-status --cached $against -- | cut -c3-` ; do
    # Check if the file contains one of the words in LIST
    if grep -w *$LIST* $FILE; then
      echo $FILE."Ninguno de estos carácteres es valido => 'áâàéèêíìîóòôúùû'"
      exit 1
    fi
      done
exit 
